/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.4 at Thu Oct 17 11:31:15 2019. */

#ifndef PB_TRY_ENC_PB_H_INCLUDED
#define PB_TRY_ENC_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Peri {
    pb_callback_t dev_name;
    float value;
/* @@protoc_insertion_point(struct:Peri) */
} Peri;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Peri_init_default                        {{{NULL}, NULL}, 0}
#define Peri_init_zero                           {{{NULL}, NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Peri_dev_name_tag                        1
#define Peri_value_tag                           2

/* Struct field encoding specification for nanopb */
extern const pb_field_t Peri_fields[3];

/* Maximum encoded size of messages (where known) */
/* Peri_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define TRY_ENC_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
