/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Thu Oct 17 11:31:15 2019. */

#include "try_enc.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Peri_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, Peri, dev_name, dev_name, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, Peri, value, dev_name, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
